### ISSUE TITLE
None

### ISSUE THREAD

**Issue by PhearTheCeal** [PhearTheCeal/Volafile-API#52]
```
The issue applies to all files posted across rooms of the type: archive, book, other. (could be more..)

For example, these files:
@OaYQP6l8VEUBiQ
@nGwYP6p8VEU8lg
@dSywPap8VEXPig 

Vola will give this info, excluding their types:

{'size': 10197440, 'user': 'MySpeshul', 'name': 'Ergo Clearing Cherry G80-3000LQC keyboard.zip', 'id': 'OaYQP6l8VEUBiQ', 'expires': 1425344009547}
{'size': 270312, 'user': 'cr4k3', 'name': 'nsa-ant-usb.pdf', 'id': 'nGwYP6p8VEU8lg', 'expires': 1425416412973}
{'size': 6207536, 'user': 'TheJIDF', 'name': 'idman623build2.exe', 'id': 'dSywPap8VEXPig', 'expires': 1425354057899}

Volapi shits itself when it tries to do:

def add_info(self, info):
    self._type = self._find_type(info) # <- Returns None
    self._info = info[self._type] # <- KeyError: None
    ...


Full error:

Exception in callback WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at /usr/local/lib/python3.4/site-packages/autobahn/asyncio/websocket.py:99
handle: <Handle WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at /usr/local/lib/python3.4/site-packages/autobahn/asyncio/websocket.py:99>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/asyncio/events.py", line 119, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.4/site-packages/autobahn/asyncio/websocket.py", line 103, in process
    self._dataReceived(data)
  File "/usr/local/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 1293, in _dataReceived
    self.consumeData()
  File "/usr/local/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 1308, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/usr/local/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 1460, in processData
    return self.processDataHybi()
  File "/usr/local/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 1771, in processDataHybi
    fr = self.onFrameEnd()
  File "/usr/local/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 1898, in onFrameEnd
    self._onMessageEnd()
  File "/usr/local/lib/python3.4/site-packages/autobahn/asyncio/websocket.py", line 150, in _onMessageEnd
    res = self.onMessageEnd()
  File "/usr/local/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 729, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/usr/local/lib/python3.4/site-packages/autobahn/asyncio/websocket.py", line 155, in _onMessage
    res = self.onMessage(payload, isBinary)
  File "/usr/local/lib/python3.4/site-packages/volapi/volapi.py", line 262, in onMessage
    self.conn.on_message(new_data)
  File "/usr/local/lib/python3.4/site-packages/volapi/volapi.py", line 352, in on_message
    self.room.add_data(json_data)
  File "/usr/local/lib/python3.4/site-packages/volapi/volapi.py", line 600, in add_data
    file.add_info(data)
  File "/usr/local/lib/python3.4/site-packages/volapi/volapi.py", line 966, in add_info
    self._info = info[self._type]
KeyError: None
```

**Comment by SkaarjK** [comment]
Adding to this, quoting 2 or more files of any type from another room in a single message will lock up Volapi when it tries to retrieve their info.  This does not happen if you first quote those files individually.

**Comment by SkaarjK** [comment]
I made sure to use the latest Volapi in this test.  I quoted 2 files from a different room and got the following output:

```
<Msg(MOTD,SCRIPT TESTING ROOM!)>
<Msg(Daed,test)>
<Msg(Daed,@oJlrP6cKVEU0H @0OVkP6cKVEU1H)>
<File(oJlrP6cKVEU0H,9304,ptc,2001.jpg)>
```

Only the first file's info was listed and then the script stopped functioning altogether.  No crash, it just stalled.  Here's the script I ran:

```python
from volapi import Room

def listen(room):

    def onchat(msg):
        print(msg)
        if msg.files:
            for file in msg.files:
                print(file)

    with Room(room) as r:
        r.add_listener("chat", onchat)
        r.listen()

if __name__ == "__main__":

    import sys

    room = ""
    if not len(sys.argv) > 1:
        print("Usage ./test.py <room>")
        sys.exit(0)
    else:
        room = sys.argv[1]

    listen(room)
```

**Comment by PhearTheCeal** [comment]
Well, my guess is that it is getting trapped on line 960
```python
self._event.wait()
```
And the call on line 600
```python
file.add_info(data)
```
is never getting called for the second file (for some reason). So the lock is never being released.

**Comment by RealDolos** [comment]
@SkaarjK Your test script was helpful. Next time ping me directly if you want to get shit done.
Pull my koksuckers branch of wait for ptc to commit something, anything xD
